import {  Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";


const poppins=Poppins({
subsets:['latin'],
variable:'poppings-font',
weight:['400','500','600','700','800','900']
})



export const metadata = {
  title: "Pixgen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable
      }  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        
        <main className="max-w-7xl mx-auto w-[90%]">
          {children}
        </main>
        
        <Footer/>
        </body>
    </html>
  );
}
